name: PermissionsYaml
main: com.github.neapovil.permissionsyaml.PermissionsYaml
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/permissions-yaml
depend:
  - CommandAPI
permissions:
  permissionsyaml.command:
    default: op
